// packages/menzies-design-wash-ui/src/primitives/SearchSelect.tsx
import {
  useEffect,
  useId,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react'
import { Check, ChevronsUpDown, Search } from '../icons'
import {
  DROPDOWN_PANEL_OVERFLOW,
  DROPDOWN_PANEL_Z,
  dropdownPanelStyle,
  dropdownPlacementClassName,
} from '../lib/dropdownPlacement'
import { useDropdownPlacement } from '../hooks/useDropdownPlacement'

export type SearchSelectOption = {
  value: string
  label: string
  disabled?: boolean
}

export type SearchSelectProps = {
  options: readonly (string | SearchSelectOption)[]
  label?: ReactNode
  placeholder?: string
  required?: boolean
  disabled?: boolean
  /** Controlled selected value (option value). */
  value?: string | null
  /** Uncontrolled initial value. */
  defaultValue?: string | null
  onChange?: (value: string | null) => void
  /** Called when an option is picked (same as onChange with a string). */
  onPick?: (value: string) => void
  emptyMessage?: string
  filterPlaceholder?: string
  triggerClassName?: string
  inputClassName?: string
  className?: string
  /** Keep the menu open (demos / forced preview). */
  forceOpen?: boolean
  /** Initial filter query (demos / empty-state previews). */
  defaultQuery?: string
  id?: string
}

function normalizeOptions(
  options: readonly (string | SearchSelectOption)[],
): SearchSelectOption[] {
  return options.map((opt) =>
    typeof opt === 'string' ? { value: opt, label: opt } : opt,
  )
}

function filterText(query: string, haystack: string) {
  return haystack.toLowerCase().includes(query.trim().toLowerCase())
}

/**
 * Searchable select (combobox): trigger + filter field + scrollable menu.
 * Placement flips top/bottom from viewport space (bottom default) and caps
 * panel height so the list scrolls instead of overflowing the page.
 */
export function SearchSelect({
  options,
  label,
  placeholder = 'Choose…',
  required = false,
  disabled = false,
  value: valueProp,
  defaultValue = null,
  onChange,
  onPick,
  emptyMessage = 'No options match.',
  filterPlaceholder = 'Type to filter…',
  triggerClassName = '',
  inputClassName = '',
  className = '',
  forceOpen = false,
  defaultQuery = '',
  id,
}: SearchSelectProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const searchRef = useRef<HTMLInputElement>(null)
  const listId = useId()
  const autoId = useId()
  const labelId = id ?? autoId

  const normalized = normalizeOptions(options)
  const [open, setOpen] = useState(forceOpen)
  const [query, setQuery] = useState(defaultQuery)
  const [uncontrolled, setUncontrolled] = useState<string | null>(defaultValue)
  const controlled = valueProp !== undefined
  const value = controlled ? valueProp : uncontrolled

  const menuOpen = (open || forceOpen) && !disabled
  const placement = useDropdownPlacement(rootRef, menuOpen, {
    panelWidth: 448,
    panelHeight: 320,
  })

  useEffect(() => {
    if (forceOpen) setOpen(true)
  }, [forceOpen])

  useEffect(() => {
    if (!menuOpen) return

    function onPointerDown(event: PointerEvent) {
      const el = rootRef.current
      if (!el) return
      if (event.target instanceof Node && !el.contains(event.target)) {
        setOpen(false)
      }
    }

    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Escape') setOpen(false)
    }

    document.addEventListener('pointerdown', onPointerDown)
    document.addEventListener('keydown', onKeyDown)
    return () => {
      document.removeEventListener('pointerdown', onPointerDown)
      document.removeEventListener('keydown', onKeyDown)
    }
  }, [menuOpen])

  useEffect(() => {
    if (menuOpen) searchRef.current?.focus()
  }, [menuOpen])

  const selected = normalized.find((opt) => opt.value === value) ?? null

  const matches = normalized.filter((opt) => {
    if (!query.trim()) return true
    return filterText(query, opt.label) || filterText(query, opt.value)
  })

  function commit(next: string) {
    if (!controlled) setUncontrolled(next)
    onChange?.(next)
    onPick?.(next)
    setQuery('')
    if (!forceOpen) setOpen(false)
  }

  function toggle() {
    if (disabled) return
    setOpen((prev) => !prev)
  }

  const rootClass = dropdownPlacementClassName(
    placement,
    `dropdown-no-hover w-full max-w-md ${menuOpen ? 'dropdown-open' : ''} ${className}`.trim(),
  )

  return (
    <div ref={rootRef} className={rootClass}>
      <label className="form-control w-full" htmlFor={undefined}>
        {label ? (
          <span className="label">
            <span className="label-text" id={`${labelId}-label`}>
              {label}
              {required ? (
                <span
                  className="text-error align-top text-sm leading-none"
                  aria-hidden="true"
                >
                  *
                </span>
              ) : null}
            </span>
          </span>
        ) : null}
        <button
          type="button"
          role="combobox"
          aria-expanded={menuOpen}
          aria-controls={listId}
          aria-haspopup="listbox"
          aria-required={required || undefined}
          aria-labelledby={label ? `${labelId}-label` : undefined}
          disabled={disabled}
          className={`btn w-full justify-between border-ink-border font-normal cursor-pointer ${
            disabled ? 'btn-disabled cursor-not-allowed' : ''
          } ${triggerClassName}`}
          onClick={toggle}
        >
          <span
            className={selected ? 'truncate' : 'truncate text-base-content/50'}
          >
            {selected?.label ?? placeholder}
          </span>
          <ChevronsUpDown
            className="size-4 shrink-0 opacity-60"
            strokeWidth={2}
          />
        </button>
        {required ? (
          <input
            type="text"
            className="sr-only"
            tabIndex={-1}
            required
            value={value ?? ''}
            onChange={() => undefined}
            aria-hidden="true"
          />
        ) : null}
      </label>

      {menuOpen ? (
        <div
          className={`dropdown-content ${DROPDOWN_PANEL_Z} ${
            placement.top ? 'mb-1' : 'mt-1'
          } w-full max-w-[min(100vw-1rem,28rem)] rounded-box border border-ink-border bg-base-100 p-2 shadow-[var(--shadow-paper-md)] ${DROPDOWN_PANEL_OVERFLOW}`}
          style={dropdownPanelStyle(placement) as CSSProperties}
        >
          <label className="input input-sm mb-2 w-full cursor-text border-ink-border">
            <Search className="size-3.5 shrink-0 opacity-60" strokeWidth={2} />
            <input
              ref={searchRef}
              type="search"
              value={query}
              placeholder={filterPlaceholder}
              className={`grow cursor-text ${inputClassName}`}
              aria-label={
                typeof label === 'string' ? `Filter ${label}` : 'Filter options'
              }
              aria-controls={listId}
              onChange={(event) => setQuery(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === 'Escape') {
                  event.stopPropagation()
                  setOpen(false)
                }
              }}
            />
          </label>
          <ul
            id={listId}
            role="listbox"
            className="menu w-full overflow-y-auto overflow-x-hidden rounded-box p-0"
            tabIndex={-1}
          >
            {matches.length === 0 ? (
              <li className="px-3 py-2 text-sm text-ink-muted">{emptyMessage}</li>
            ) : (
              matches.map((opt) => {
                const active = value === opt.value
                return (
                  <li key={opt.value} role="option" aria-selected={active}>
                    <button
                      type="button"
                      disabled={opt.disabled}
                      className={`cursor-pointer ${active ? 'active' : ''} ${
                        opt.disabled ? 'cursor-not-allowed opacity-50' : ''
                      }`}
                      onMouseDown={(event) => event.preventDefault()}
                      onClick={() => {
                        if (!opt.disabled) commit(opt.value)
                      }}
                    >
                      <span className="truncate">{opt.label}</span>
                      {active ? (
                        <Check className="size-4 opacity-70" strokeWidth={2} />
                      ) : null}
                    </button>
                  </li>
                )
              })
            )}
          </ul>
        </div>
      ) : null}
    </div>
  )
}

// apps/demo/src/snippets/svelte/search-select/SearchSelect.svelte
<script lang="ts">
	type Option = { value: string; label: string; disabled?: boolean }

	type Props = {
		options?: (string | Option)[]
		value?: string | null
		label?: string
		placeholder?: string
		filterPlaceholder?: string
		emptyMessage?: string
		/** Seeded into the filter when the menu opens (not forced open). */
		defaultQuery?: string
		disabled?: boolean
		required?: boolean
		triggerClass?: string
		inputClass?: string
	}

	let {
		options = [
			'Ultramarine',
			'Yellow ochre',
			'Alizarin crimson',
			'Viridian',
			'Burnt sienna',
			'Cobalt blue',
			'Cerulean',
			'Quinacridone rose'
		],
		value = $bindable<string | null>(null),
		label = 'Pigment',
		placeholder = 'Search pigments…',
		filterPlaceholder = 'Type to filter…',
		emptyMessage = 'No options match.',
		defaultQuery = '',
		disabled = false,
		required = false,
		triggerClass = '',
		inputClass = ''
	}: Props = $props()

	let open = $state(false)
	let query = $state('')
	let rootEl: HTMLDivElement | undefined = $state()
	const listboxId = `search-select-listbox-${Math.random().toString(36).slice(2, 9)}`

	const normalized = $derived(
		options.map((o) => (typeof o === 'string' ? { value: o, label: o } : o))
	)

	const filtered = $derived(
		normalized.filter((o) => o.label.toLowerCase().includes(query.trim().toLowerCase()))
	)

	const selected = $derived(normalized.find((o) => o.value === value))

	function commit(next: string) {
		if (disabled) return
		value = next
		open = false
		query = ''
	}

	function toggle() {
		if (disabled) return
		open = !open
		if (open) query = defaultQuery
		else query = ''
	}

	$effect(() => {
		if (!open) return
		function onDoc(e: MouseEvent) {
			if (rootEl && !rootEl.contains(e.target as Node)) open = false
		}
		function onKey(e: KeyboardEvent) {
			if (e.key === 'Escape') open = false
		}
		document.addEventListener('mousedown', onDoc)
		document.addEventListener('keydown', onKey)
		return () => {
			document.removeEventListener('mousedown', onDoc)
			document.removeEventListener('keydown', onKey)
		}
	})
</script>

<div
	bind:this={rootEl}
	class="dropdown dropdown-no-hover w-full max-w-md {open ? 'dropdown-open' : ''} {disabled
		? 'pointer-events-none opacity-60'
		: ''}"
>
	<label class="form-control w-full">
		{#if label}
			<span class="label">
				<span class="label-text">
					{label}
					{#if required}
						<span class="text-error align-top text-sm leading-none" aria-hidden="true">*</span>
					{/if}
				</span>
			</span>
		{/if}
		<button
			type="button"
			class="btn w-full justify-between border-ink-border font-normal cursor-pointer {triggerClass} {disabled
				? 'btn-disabled cursor-not-allowed'
				: ''}"
			role="combobox"
			aria-expanded={open}
			aria-controls={open ? listboxId : undefined}
			aria-haspopup="listbox"
			aria-required={required || undefined}
			{disabled}
			onclick={toggle}
		>
			<span class="min-w-0 flex-1 truncate {selected ? '' : 'text-base-content/50'}">
				{selected?.label ?? placeholder}
			</span>
			<svg
				class="size-4 shrink-0 opacity-60"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				aria-hidden="true"
			>
				<path d="m7 15 5 5 5-5" />
				<path d="m7 9 5-5 5 5" />
			</svg>
		</button>
	</label>
	{#if open}
		<div
			class="dropdown-content z-[80] mt-1 w-full max-w-[min(100vw-1rem,28rem)] overflow-y-auto overflow-x-hidden rounded-box border border-ink-border bg-base-100 p-2 shadow-[var(--shadow-paper-md)]"
		>
			<label class="input input-sm mb-2 w-full cursor-text border-ink-border">
				<svg
					class="size-3.5 shrink-0 opacity-60"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					aria-hidden="true"
				>
					<path d="m21 21-4.34-4.34" />
					<circle cx="11" cy="11" r="8" />
				</svg>
				<input
					type="search"
					class="grow cursor-text {inputClass}"
					placeholder={filterPlaceholder}
					bind:value={query}
					aria-label="Filter {label}"
				/>
			</label>
			<ul
				id={listboxId}
				class="menu max-h-52 w-full overflow-y-auto overflow-x-hidden rounded-box p-0"
				role="listbox"
				tabindex="-1"
			>
				{#if filtered.length === 0}
					<li class="px-3 py-2 text-sm text-ink-muted">{emptyMessage}</li>
				{:else}
					{#each filtered as opt (opt.value)}
						<li role="option" aria-selected={value === opt.value}>
							<button
								type="button"
								class="cursor-pointer {value === opt.value ? 'active' : ''} {opt.disabled
									? 'cursor-not-allowed opacity-50'
									: ''}"
								disabled={opt.disabled}
								onclick={() => commit(opt.value)}
							>
								<span class="truncate">{opt.label}</span>
								{#if value === opt.value}
									<svg
										class="size-4 opacity-70"
										viewBox="0 0 24 24"
										fill="none"
										stroke="currentColor"
										stroke-width="2"
										aria-hidden="true"
									>
										<path d="M20 6 9 17l-5-5" />
									</svg>
								{/if}
							</button>
						</li>
					{/each}
				{/if}
			</ul>
		</div>
	{/if}
</div>
